# Generated by Django 5.2.8 on 2025-11-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecommande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articlecommande',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='articlecommande',
            table=None,
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='commande',
            table=None,
        ),
        migrations.AlterModelTable(
            name='produit',
            table=None,
        ),
    ]
