# Generated by Django 5.2.8 on 2025-11-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_articlecommande_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom', 'prenom'], 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='articlecommande',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='articlecommande',
            name='modifie_le',
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.commande'),
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.client'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='produit',
            table='produit',
        ),
    ]
