# Generated by Django 5.2.8 on 2025-11-26 19:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_client_options_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
